name: Build and Test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 13.8.0
        uses: actions/setup-node@v1
        with:
          node-version: '13.8.0'
      - run: yarn install
      - run: yarn build
      - run: yarn test:CI
        env:
          CI: true